import re, time
from playwright.sync_api import Page, expect
from pages import HomePage

def test_tc1(home_page: HomePage) -> None:
    # home_page.accept_cookies()
    time.sleep(3)
    
# def test_example(page: Page) -> None:
#     page.goto("https://automationexercise.com/")
#     expect(page.locator("div").filter(has_text="Здравствуйте!Этот сайт запрашивает у вас согласие на использование ваших данныхП").nth(3)).to_be_visible()
#     expect(page.get_by_role("dialog", name="Этот сайт запрашивает у вас согласие на использование ваших данных")).to_be_visible()
#     page.get_by_role("button", name="Соглашаюсь").click()
#     expect(page.get_by_role("heading", name="AutomationExercise")).to_be_visible()
#     page.get_by_role("link", name=" Signup / Login").click()
#     expect(page.get_by_role("heading", name="New User Signup!")).to_be_visible()
#     page.get_by_role("textbox", name="Name").click()
#     page.get_by_role("textbox", name="Name").fill("test_user")
#     page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").click()
#     page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").fill("test_user@example.com")
#     page.get_by_role("button", name="Signup").click()
#     expect(page.get_by_text("Email Address already exist!")).to_be_visible()
#     page.get_by_role("textbox", name="Name").click()
#     page.get_by_role("textbox", name="Name").fill("test_user")
#     page.get_by_role("textbox", name="Name").press("Tab")
#     page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").fill("test_user123123@example.com")
#     page.get_by_role("button", name="Signup").click()
#     page.goto("https://automationexercise.com/signup")
#     expect(page.get_by_text("Enter Account Information")).to_be_visible()
#     page.get_by_role("radio", name="Mr.").check()
#     page.get_by_role("textbox", name="Name *", exact=True).click()
#     page.get_by_role("textbox", name="Password *").click()
#     page.get_by_role("textbox", name="Password *").fill("test_user123123")
#     page.locator("#days").select_option("2")
#     page.locator("#months").select_option("5")
#     page.locator("#years").select_option("1978")
#     page.get_by_role("checkbox", name="Sign up for our newsletter!").check()
#     page.get_by_role("checkbox", name="Receive special offers from").check()
#     page.get_by_role("textbox", name="First name *").click()
#     page.get_by_role("textbox", name="First name *").fill("Test")
#     page.get_by_role("textbox", name="First name *").press("Tab")
#     page.get_by_role("textbox", name="Last name *").fill("User")
#     page.get_by_role("textbox", name="Last name *").press("Tab")
#     page.get_by_role("textbox", name="Company", exact=True).fill("MyCompany")
#     page.get_by_role("textbox", name="Address * (Street address, P.").click()
#     page.get_by_role("textbox", name="Address * (Street address, P.").fill("188 Florida Ave, 40102")
#     page.get_by_role("textbox", name="Address * (Street address, P.").press("Tab")
#     page.get_by_role("textbox", name="Address 2").fill("123/45")
#     page.get_by_label("Country *").select_option("United States")
#     page.get_by_role("textbox", name="State *").click()
#     page.get_by_role("textbox", name="State *").fill("Iowa")
#     page.get_by_role("textbox", name="State *").press("Tab")
#     page.get_by_role("textbox", name="City * Zipcode *").fill("Orange City")
#     page.get_by_role("textbox", name="City * Zipcode *").press("Tab")
#     page.locator("#zipcode").click()
#     page.locator("#zipcode").fill("10457")
#     page.get_by_role("textbox", name="Mobile Number *").click()
#     page.get_by_role("textbox", name="Mobile Number *").fill("789789789")
#     page.get_by_role("button", name="Create Account").click()
#     expect(page.get_by_text("Account Created!")).to_be_visible()
#     page.get_by_role("link", name="Continue").click()
#     expect(page.get_by_text("Logged in as test_user")).to_be_visible()
#     page.get_by_role("link", name=" Delete Account").click()
#     expect(page.get_by_text("Account Deleted!")).to_be_visible()
#     page.get_by_role("link", name="Continue").click()
